/**
 * @flow
 */

 export default {
   DELETE_SONG: 'DELETE_SONG',
   SET_SONGS: 'SET_SONGS',
   NEXT_SONG: 'NEXT_SONG',
   PREVIOUS_SONG: 'PREVIOUS_SONG',
   PLAY_SONG: 'PLAY_SONG',
   PAUSE_SONG: 'PAUSE_SONG',
   RESUME_SONG: 'RESUME_SONG',
   STOP_SONG: 'STOP_SONG',
   UPDATE_ELAPSED_TIME: 'UPDATE_ELAPSED_TIME',
   SEEK_SONG: 'SEEK_SONG',
 };
